development:
  domain: localhost
  scheme: http
  port: 8443
  secret: secret
test:
  domain: localhost
  scheme: http
  port: 8443
  secret: secret
production:
  domain: localhost
  scheme: http
  port: 8443
  secret: secret