development:
  domain: localhost
  scheme: http
  port: 8443
  secret: secret
test:
  secret: fnADnyj1rVACAN2-9LgnRzEw70HAHJLK18aUhUTU
production:
  domain: localhost
  scheme: http
  port: 8443
  secret: secret